const express=require('express'),crypto=require('crypto'),path=require('path'),Database=require('better-sqlite3');
const app=express(),db=new Database('tapview.db'),PORT=process.env.PORT||3000,BOT_TOKEN=process.env.BOT_TOKEN||'';
app.use(express.json());app.use(express.static(path.join(__dirname,'public')));
db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY,balance INTEGER DEFAULT 0);
CREATE TABLE IF NOT EXISTS ads(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS history(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER,type TEXT,amount INTEGER,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS withdrawals(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER,method TEXT,account TEXT,amount INTEGER,status TEXT DEFAULT 'pending',created_at TEXT DEFAULT CURRENT_TIMESTAMP);`);
function user(req){if(!BOT_TOKEN)return null;const s=req.get('X-Telegram-Init-Data'),p=new URLSearchParams(s||''),h=p.get('hash');if(!h)return null;p.delete('hash');const data=[...p].sort().map(x=>x[0]+'='+x[1]).join('\n'),key=crypto.createHmac('sha256','WebAppData').update(BOT_TOKEN).digest(),calc=crypto.createHmac('sha256',key).update(data).digest('hex');if(calc!==h)return null;return JSON.parse(p.get('user')||'{}').id}
function auth(req,res,next){let id=user(req);if(!id)return res.status(401).json({error:'Invalid Telegram session'});db.prepare('INSERT OR IGNORE INTO users(id) VALUES(?)').run(id);req.uid=id;next()}
app.get('/api/me',auth,(req,res)=>{const u=db.prepare('SELECT balance FROM users WHERE id=?').get(req.uid),n=db.prepare("SELECT COUNT(*) c FROM ads WHERE user_id=? AND date(created_at)=date('now')").get(req.uid).c,h=db.prepare('SELECT type,amount,created_at FROM history WHERE user_id=? ORDER BY id DESC LIMIT 50').all(req.uid);res.json({balance:u.balance,adsToday:n,history:h,referralLink:`${req.protocol}://${req.get('host')}/?ref=${req.uid}`})});
app.post('/api/ads/complete',auth,(req,res)=>{const n=db.prepare("SELECT COUNT(*) c FROM ads WHERE user_id=? AND date(created_at)=date('now')").get(req.uid).c;if(n>=30)return res.status(429).json({error:'Daily limit reached'});db.prepare('INSERT INTO ads(user_id) VALUES(?)').run(req.uid);db.prepare('UPDATE users SET balance=balance+15 WHERE id=?').run(req.uid);db.prepare('INSERT INTO history(user_id,type,amount) VALUES(?,?,?)').run(req.uid,'Ad reward',15);res.json({reward:15})});
app.post('/api/withdraw',auth,(req,res)=>{let {method,account,amount}=req.body||{};amount=Number(amount);if(!['bKash','Nagad','Binance'].includes(method)||!account||amount<1100)return res.status(400).json({error:'Invalid request'});let u=db.prepare('SELECT balance FROM users WHERE id=?').get(req.uid);if(amount>u.balance)return res.status(400).json({error:'Insufficient balance'});db.prepare('UPDATE users SET balance=balance-? WHERE id=?').run(amount,req.uid);db.prepare('INSERT INTO withdrawals(user_id,method,account,amount) VALUES(?,?,?,?)').run(req.uid,method,account,amount);db.prepare('INSERT INTO history(user_id,type,amount) VALUES(?,?,?)').run(req.uid,'Withdrawal',-amount);res.json({message:'Withdrawal request submitted'})});
app.listen(PORT,()=>console.log('Server running on '+PORT));